.devcontainer/Dockerfile, .devcontainer/devcontainer.json
Add a [VSCode dev container](https://code.visualstudio.com/docs/devcontainers/containers) for Soroban development.
This simply takes the Rust dev container from Microsoft and installs `soroban-cli` and the appropriate wasm target.
If the [quickstart Docker image](https://github.com/stellar/quickstart) is run outside the container, its RPC endpoint is available as `http://host.docker.internal:8000/soroban/rpc`.
=> Add a dev container for Soroban development

.github/workflows/main.yml, solarkraft/eslint.config.js, solarkraft/package-lock.json, solarkraft/package.json, solarkraft/src/main.ts
Closes #16. This PR adds `eslint` to check for common JS/TS pitfalls.
=> add eslint

solarkraft/eslint.config.js, solarkraft/src/main.ts
Towards #25. This PR adds one CLI command `txs`. The main purpose is just to get the argument parser work. I still have to think through the CLI commands.
=> add a simple CLI mock

solarkraft/src/state/value.ts, solarkraft/test/state/value.test.ts
Partially addresses #23 (missing compound values, e.g. Map/Vec)
=> Basic values and tests

solarkraft/src/fetch.ts, solarkraft/src/list.ts, solarkraft/src/main.ts, solarkraft/src/verify.ts
Closes #25. I have thought a bit about the CLI commands that we would need. Here is the first mock that contains `fetch`, `list`, and `verify`. To check this PR, simply pull it, compile and play with `solarkraft`.
=> Add mock CLI commands

solarkraft/.devcontainer/Dockerfile, solarkraft/.devcontainer/devcontainer.json
There are no Z3 binaries for linux/aarch64 for now: https://github.com/Z3Prover/z3/issues/7201
Pin the devcontainer platform to `linux/amd64` to work around it.
=> Pin devcontainer platform to linux/amd64

solarkraft/src/instrument.ts, solarkraft/src/main.ts, solarkraft/src/verify.ts, solarkraft/test/e2e/verify.test.ts
Remove hardcoded state in monitor executor and instead read state from ITF.
Introduces a transitional `--state` argument to `verify` that we can replace with convention when the fetcher writes ITF.
Closes #42
=> Read ITF in monitor executor

solarkraft/src/instrument.ts, solarkraft/src/verify.ts, solarkraft/test/e2e/tla/timelock_mon2.tla, solarkraft/test/e2e/tla/timelock_state.itf.json, solarkraft/test/e2e/verify.test.ts, solarkraft/test/unit/instrument.test.ts, solarkraft/test/unit/verify.instrumentedMonitor.ts
Only instrument state variables that are declared in the monitor spec.
Otherwise, Apalache fails with an error on the undeclared but instrumented variables.
Also, add some code for decoding [ITF `#bigint`](https://apalache.informal.systems/docs/adr/015adr-trace.html#revisions).
=> Instrument only monitor variables

.github/workflows/main.yml, ContractExamples/contracts/setter/README.md, ContractExamples/contracts/setter/src/lib.rs, ContractExamples/contracts/setter/src/test.rs, ContractExamples/scripts/setter-populate.sh
This PR adds a bash script for populating the `Setter` contract with data, so we can use it in our integration tests.
=> Add a script to populate the Setter contract

ContractExamples/contracts/setter/src/lib.rs, solarkraft/package-lock.json, solarkraft/package.json, solarkraft/src/fetch.ts, solarkraft/src/fetcher/callDecoder.ts, solarkraft/src/fetcher/storage.ts, solarkraft/src/main.ts, solarkraft/test/integration/callDecoder.test.ts
This PR presents a working implementation of transaction decoder. The core of this contribution is:
The integration test is fragile as the test data will disappear after 1 month or when the testnet is reset. We have to find a more stable solution. However, for the development purposes, it should work.
=> the first working version of transaction fetcher

doc/adr002-storage.md
This PR documents a simple design for storing the transactions that are to be extracted by the fetcher.
=> add ADR002 to document the storage

solarkraft/src/fetcher/storage.ts, solarkraft/test/unit/storage.test.ts
=> add a simple implementation of ADR002

solarkraft/src/fetch.ts, solarkraft/src/fetcher/storage.ts, solarkraft/src/main.ts, solarkraft/test/unit/storage.test.ts
This PR adds relatively small changes on top of #55. The fetcher is fetching the transactions and saving them in the storage. For example:
```sh
$ solarkraft fetch --rpc https://horizon-testnet.stellar.org --id CC22QGTOUMERDNIYN7TPNX3V6EMPHQXVSRR3XY56EADF7YTFISD2ROND --height 1638368
Target contract: CC22QGTOUMERDNIYN7TPNX3V6EMPHQXVSRR3XY56EADF7YTFISD2ROND...
Last cached height: 1638598
Fetching fresh transactions from: https://horizon-testnet.stellar.org...
Fetching the ledger for 1638368
Fetching transactions indefinitely. Close with Ctrl-C.
+ save: 1638369
+ save: 1638371
+ save: 1638370
+ save: 1638372
+ save: 1638373
+ save: 1638374
+ save: 1638375
+ save: 1638376
+ save: 1638378
+ save: 1638377
+ save: 1638379
+ save: 1638380
+ save: 1638381
+ save: 1638382
+ save: 1638383
= at: …
```
=> working fetcher CLI

solarkraft/src/fetcher/storage.ts, solarkraft/src/list.ts, solarkraft/src/main.ts, solarkraft/test/e2e/list.test.ts
This PR implements `solarkraft list`. Since our file storage is very simple, the implementation is also simple.
=> add a simple implementation of `solarkraft list`

solarkraft/src/instrument.ts, solarkraft/test/unit/instrument.test.ts
Add support for all Soroban [primitive types](https://developers.stellar.org/docs/learn/smart-contract-internals/types/built-in-types#primitive-types), plus `Bytes`, `BytesN` and `Address` in the checker.
In addition to the unit tests here, I have an on-chain E2E test based on the setter contract that I'll add in a follow-up PR once all its fields/types are supported.
Next step is to address `Map` and `Vec` (#46), then enums and structs (#73).
=> Support all Soroban primitive types

solarkraft/.devcontainer/Dockerfile, solarkraft/.devcontainer/devcontainer.json
2 small improvements to the Solarkraft devcontainer:
1. include the Apalache in the `PATH` env
2. install the TLA+ VSCode extension (nightly, because the regular release is heavily outdated and I couldn't get it to install inside the devcontainer)
=> Small devcontainer improvements

solarkraft/src/fetch.ts, solarkraft/test/e2e/fetch.test.ts
As promised, here is an e2e test for the fetcher
=> add a fetcher test

solarkraft/src/environment.d.ts, solarkraft/src/verify.ts
closes #34
Instead of looking at a fixed directory, attempts to read the `$APALACHE_HOME` environment variable.
=> Fixes hardcoded Apalache path

solarkraft/src/verify.ts
Found this while doing the demo, since `VerificationStatus::Unknown` absorbs `NoViolation`, the initial fold-value must be a `NoViolation`, since otherwise `Unknown` (initial) + `NoViolation` (actual result) give an `Unknown`, instead of a `NoViolation`
=> Correctness fix in default status

solarkraft/src/verifier/instrument.ts, solarkraft/src/verifier/invokeAlert.ts, solarkraft/src/verify.ts, solarkraft/test/e2e/invokeAlert.test.ts, solarkraft/test/unit/instrument.test.ts
Small refactoring that clears up the `./src/` root, to only contain entry points to the main commands `fetch`, `list`, and `verify`.
All other source files are moved to subdirectories.
=> Move non-commands to subdir

ContractExamples/Cargo.toml, ContractExamples/contracts/alert/Cargo.toml, ContractExamples/contracts/megacontract/Cargo.toml, ContractExamples/contracts/setter/Cargo.toml
- Update git submodule `soroban-examples` to latest tag v21.6.0: https://github.com/stellar/soroban-examples/tree/v21.6.0
- Upgrade `soroban-sdk` dependency of local contracts to v21.6.0
=> Upgrade soroban-examples / soroban-sdk to v21.6.0

solarkraft/test/e2e/fetch.test.ts, solarkraft/test/e2e/invokeAlert.test.ts, solarkraft/test/integration/callDecoder.test.ts
After the recent testnet reset, redeploy the test contracts and update contract IDs and transaction hashes.
=> Update contract IDs and transaction hashes after testnet reset

ContractExamples/contracts/setter/src/lib.rs, solarkraft/src/fetcher/callDecoder.ts, solarkraft/src/fetcher/storage.ts, solarkraft/test/e2e/list.test.ts, solarkraft/test/integration/callDecoder.test.ts, solarkraft/test/unit/instrument.test.ts, solarkraft/test/unit/storage.test.ts
Preparatory change towards #54.
Closes #121
Closes #126
In the fetcher, extract **all** ledger entry changes from a transaction, i.e, including
- changes to temporary and persistent storage, and
- changes to other contracts than the (root-)invoked contract.
The result is two (pre- & post-state) nested maps keyed by
1. contract address
2. 'instance' | 'persistent' | 'temporary'
3. the `ScVal` key, SDK-transformed to a native JS val and `.toString()`ed
The resulting maps are only propagated to Solarkraft on-disk storage, and not yet used for instrumentation. In particular, we still populate `fields` and `oldFields` by projecting the above maps to the instance storage of the root-invocation contract ID.
**Tests:**
Update the setter contract to store all fields in instance, persistent and …
=> Extract temporary and permanent storage changes

solarkraft/test/integration/callDecoder.test.ts
Our fetcher integration test so far relies on hard-coded transaction hashes that were pre-populated by the `setter-popluate.sh` script. Those tx hashes need to be manually updated whenever the testnet resets, or when the setter contract is updated.
This PR introduces programmatic population of the deployed setter contract to achieve a more stable integration test: On each integration test run, a fresh copy of the setter contract is created from its on-chain WASM code (there is a 1:n relationship between WASM code and contracts IDs). Each test then invokes a setter function of the contract, followed by fetching the respective transaction and verifying the call decoder output as before.
This could be further optimized for performance (i.e., only repopulate the contract when necessary), but …
=> Stable integration tests for the transaction fetcher

ContractExamples/contracts/setter/src/lib.rs, ContractExamples/scripts/setter-populate.sh, solarkraft/src/fetcher/callDecoder.ts, solarkraft/test/integration/callDecoder.test.ts
So far, we did not support the `ledgerEntryRemoved` ledger change type in the fetcher.
It occurs when a persistent or temporary entry is removed via `env.storage()._().remove(key)`.
Turns out it already works out-of-the-box, but this PR adds a test (including a removal function in the setter contract).
Closes #122
=> Support `ledgerEntryRemoved`

solarkraft/src/fetcher/storage.ts
Fix a type annotation and loading of storage `MultiContractStorage` maps:
`Immutable.fromJS` deeply converts all JS objects to Maps.
For deserializing storage, we want the target object to instead be
```
Map -> JS object {instance: Map, persistent: Map, temporary: Map}
```
Thus, we provide a custom loader instead.
=> Fix storage loading

solarkraft/src/verify_js.ts, solarkraft/test/e2e/verify_js_example.ts, solarkraft/test/unit/verify_js.test.ts
This is a delta to #135.
While working on #133, I realized that Stellar Asset Contracts use a different storage layout than the `soroban-examples/token` contract (in particular, they keep a struct inside the `Balance` storage, not just an `i128` amount).
In this PR, we
* move the `tokenTransferred` condition that only applies to `soroban-examples/token` out of Solarkraft, and into `verify_js_example.ts`
* provide a [CAP-46](https://github.com/stellar/stellar-protocol/blob/master/core/cap-0046.md)-compatible version of `tokenTransferred` instead
* add a [CAP-46](https://github.com/stellar/stellar-protocol/blob/master/core/cap-0046.md)-compatible condition `tokenReceived`, that checks only the receiver part of `tokenTransferred`
`tokenReceived` is necessary, because there may not be a …
=> Separate `tokenReceived` for Stellar Asset Contract

solarkraft/.devcontainer/Dockerfile, solarkraft/src/verify.ts
We were looking up `apalache-mc` under either the custom env variable `APALACHE_HOME`, or the hardcoded path `/opt/apalache`. Instead of the hardcoded path, we can simply rely on `$PATH` to find the binary.
Also improves the error message if `spawnSync` fails.
Also removes a superfluous slash in the devcontainer Dockerfile.
=> Fix Apalache path

.github/workflows/main.yml, .github/workflows/testnet.yml, .gitmodules, ContractExamples/.cargo/config.toml, ContractExamples/Cargo.toml, ContractExamples/contracts/alert/Cargo.toml, ContractExamples/contracts/megacontract/Cargo.toml, ContractExamples/contracts/setter/Cargo.toml, ContractExamples/patches/xycloans.diff, ContractExamples/patches/xycloans2.diff, ContractExamples/scripts/alert-deploy.sh, ContractExamples/scripts/build.sh, ContractExamples/scripts/prepare-timelock.sh, ContractExamples/scripts/setter-populate.sh, ContractExamples/scripts/xycloans-populate.sh, solarkraft/package-lock.json, solarkraft/package.json, solarkraft/src/fetch.ts, solarkraft/src/fetcher/callDecoder.ts, solarkraft/src/main.ts, solarkraft/src/verifier/invokeAlert.ts, solarkraft/src/verify_js.ts, solarkraft/test/e2e/invokeAlert.test.ts, solarkraft/test/integration/callDecoder.test.ts
I did not expect that it will take me so much time (like a week) to fix the CI with all the recent Soroban changes. What we have here:
Optimally, it would be great to have a smaller PR, but all these things pulled one another.
=> fixing the CI + workflow for deploying contracts to testnet

.github/workflows/main.yml, .github/workflows/testnet.yml, .gitmodules, ContractExamples/.cargo/config.toml, ContractExamples/Cargo.toml, ContractExamples/contracts/alert/Cargo.toml, ContractExamples/contracts/megacontract/Cargo.toml, ContractExamples/contracts/setter/Cargo.toml, ContractExamples/patches/xycloans.diff, ContractExamples/patches/xycloans2.diff, ContractExamples/scripts/alert-deploy.sh, ContractExamples/scripts/build.sh, ContractExamples/scripts/prepare-timelock.sh, ContractExamples/scripts/setter-populate.sh, ContractExamples/scripts/xycloans-populate.sh, solarkraft/package-lock.json, solarkraft/package.json, solarkraft/src/fetch.ts, solarkraft/src/fetcher/callDecoder.ts, solarkraft/src/main.ts, solarkraft/src/verifier/invokeAlert.ts, solarkraft/src/verify_js.ts, solarkraft/test/e2e/invokeAlert.test.ts, solarkraft/test/integration/callDecoder.test.ts
`npm` reported a high vulnerability in our dependencies. Upgrading them.
=> upgrade dependencies to avoid a high

doc/case-studies/xycloans/MCxycloans_monitor.tla, doc/case-studies/xycloans/xycloans_monitor.tla, doc/case-studies/xycloans/xycloans_types.tla
This is basically the TLA+ specification after `verify_js_example_xycloans.ts`. Apalache produces examples for `MCxycloans_monitor.tla`. However, we probably need more constraints in the spec, as the environment gets a complete update every time. We have to figure out how to produce meaningful examples.
=> minimal TLA+ spec of the xycloans monitor

solarkraft/src/aggregate.ts, solarkraft/src/aggregator/aggregator.ts, solarkraft/src/fetcher/aggregator.ts, solarkraft/src/fetcher/storage.ts, solarkraft/src/main.ts, solarkraft/test/e2e/verify.test.ts, solarkraft/test/unit/aggregator.test.ts, solarkraft/test/unit/storage.test.ts
Closes #153. This PR implements basic state aggregation. It's probably the most straightforward approach. We need this for input generation. I believe that a high-performance approach would require much more work, which we do not have in this phase.
=> implement basic state aggregation
